version: '3.8'

services:
  # API 服务器
  api-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3001:3001"
    volumes:
      - ./data:/app/data
    restart: unless-stopped