version: '3.8'

services:
  nano-banana-supermarket:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - GEMINI_API_KEY=${GEMINI_API_KEY}
        - API_BASE_URL=${API_BASE_URL}
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

# 可选：如果需要数据持久化
volumes:
  app-data: